services:
  db:
    image: postgres:16.4
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - mysql5:/var/lib/mysql
    ports:
      - "543216:5432"
    networks:
      - my-network

volumes:
  postgres:
    driver: local

networks:
  my-network:
    driver: bridge
